Enhanced_blog/Enhanced_blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
#SEO
from django.contrib.sitemaps.views import sitemap
from apps.home.sitemap import (
    EntrySitemap,
    Sitemap
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.home.urls')),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.entries.urls')),
    re_path('', include('apps.favorites.urls')),
    #urls to ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'home_app:home'
        ]
    ),
    'entries': EntrySitemap,
    # se agregan mas urls aca se crea el sitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml/',
        sitemap,
        {
            'sitemaps': sitemaps
        },
        name='django.contrib.sitemaps.views.sitemap'
        )   
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Enhanced_blog/apps/entries/urls.py
from django.urls import path

from . import views

app_name = 'urls_entries'

urlpatterns = [
    path(
        'Lista_blogs/',
        views.EntryListView.as_view(),
        name = "blog_list"
        ),
    path(
        'blog/<slug>',
        views.EntryDetailView.as_view(),
        name = "Entry"
        ),
]

Enhanced_blog/apps/favorites/urls.py
from django.urls import path

from . import views

app_name = "favorites_app"

urlpatterns = [
    path(
        'profile',
        views.FavoritesListView.as_view(),
        name = "profile"
        ),
    path(
        'add_favorites/<pk>',
        views.AddFavoriteView.as_view(),
        name = "add-favorites"
        ),
    path(
        'deletefavorites/<pk>/',
        views.FavoriteDeleteView.as_view(),
        name = "delete-favorites"
        )
    
]

Enhanced_blog/apps/home/urls.py
#
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='home',
    ),  
    path(
        'Registro_suscriptor', 
        views.SuscriberCreateView.as_view(),
        name='new_subscriber',
    ),  
    path(
        'Contactame', 
        views.ContactCreateView.as_view(),
        name='new_message',
    ),  
] 

Enhanced_blog/apps/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name='user-update-password',
    ),
    path(
        'updateUser/<pk>/',
        views.UpdateUserView.as_view(),
        name='basic_information_user_update'
    ),
    path(
        'incorrect!!/',
        views.IconcorrectPassword.as_view(),
        name = "incorrect-password"
    ),
    path(
        'contraseñaOlvidada/',
        views.RecoverPasswordListView.as_view(),
        name='forgot-password'
    )
]

Enhanced_blog/templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" action="{% url 'home_app:new_message' %}" method="POST"> {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name="full_name" id="id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="email" placeholder="Correo ..." name="email" id="id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name="message" id="id_message"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>

            <p class="grid-x align-center cell large-8"> <span class="label warning"><i class="fi-x-circle"></i> Otras formas de contacto</span> </p>
            <p class="grid-x cell align-spaced large-8" >
              <span class="label warning">Email: {{ email }}</span>
              <span class="label warning">Telefono: {{ phone }}</span>
            </p>
        </div>
      </div>
    

Enhanced_blog/templates/includes/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/myCustom.css' %}">
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="#" style="font-size: 20px; color: #0277bd;">
            SWITCHER
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{% url 'home_app:home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'urls_entries:blog_list' %}">Blog</a>
                </li>
                <li>
                <!-- user es un contextProcesor utilizado en models y views-->
                    {% if not user.is_anonymous %}
                    <a href="{% url 'favorites_app:profile' %}" class="warning button">perfil</a>
                </li>
                <li>
                    <img class="profile-img circle-profile" src="{{image_profile.url}}" alt="">
                </li>
                <li>
                    {% else %}
                    <a href="{% url 'users_app:user-login' %}" class="success button">Acceder</a>
                </li> 
                <li>
                    <img class="profile-img" src="{{avatar.url}}" alt="">
                </li>
                {% endif %}
                
            </ul>
        </div>
    </div>
</header>