Enhanced_blog/Enhanced_blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
#SEO
from django.contrib.sitemaps.views import sitemap
from apps.home.sitemap import (
    EntrySitemap,
    Sitemap
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.home.urls')),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.entries.urls')),
    re_path('', include('apps.favorites.urls')),
    #urls to ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'home_app:home'
        ]
    ),
    'entries': EntrySitemap,
    # se agregan mas urls aca se crea el sitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml/',
        sitemap,
        {
            'sitemaps': sitemaps
        },
        name='django.contrib.sitemaps.views.sitemap'
        )   
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Enhanced_blog/apps/entries/urls.py
from django.urls import path

from . import views

app_name = 'urls_entries'

urlpatterns = [
    path(
        'Lista_blogs/',
        views.EntryListView.as_view(),
        name = "blog_list"
        ),
    path(
        'blog/<slug>',
        views.EntryDetailView.as_view(),
        name = "Entry"
        ),
]

Enhanced_blog/apps/home/urls.py
#
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='home',
    ),  
    path(
        'Registro_suscriptor', 
        views.SuscriberCreateView.as_view(),
        name='new_subscriber',
    ),  
    path(
        'Contactame', 
        views.ContactCreateView.as_view(),
        name='new_message',
    ),  
] 

Enhanced_blog/apps/home/models.py
from django.db import models

# third apps
from model_utils.models import TimeStampedModel
# READ MORE ABOUT TimeStampedModel for using
# required install way pip django-model-utils
# it's not import in thirdpartyapps of base.py

class Home(TimeStampedModel):
    """Model for app home"""
    title = models.CharField(("Nombre"), max_length=50)
    description = models.TextField()
    about_title = models.CharField(("Titulo Nosotros"), max_length=50)
    about_text = models.TextField()
    contact_email = models.EmailField(("Email de Contacto"), blank = True, null = True)
    phone = models.IntegerField(("Telefono"))
    avatar_image_default = models.ImageField(("Imagen por defecto"), upload_to='avatars', blank=True)


    class Meta:
        verbose_name = "pagina Principal"
        verbose_name_plural = "pagina Principal"

    def __str__(self):
        return self.title


class Subcribers(TimeStampedModel):
    """Model for app subscriber"""
    email = models.EmailField(("Email"), max_length=254)

    class Meta:
        verbose_name = "sucriptor"
        verbose_name_plural = "sucriptores"
    
    def __str__(self):
        return self.email

class Contact(TimeStampedModel):
    """Model for app Contact"""
    full_name = models.CharField(("Nombre Completo"), max_length=60)
    email = models.EmailField(("email"), max_length=254)
    message = models.TextField(("mensaje"))

    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contacto"

    def __str__(self):
        return self.full_name
    
    

Enhanced_blog/apps/home/forms.py
from django import forms

from .models import Subcribers, Contact

class subscriberForm(forms.ModelForm):
    
    class Meta:
        model = Subcribers
        fields = (
            'email',
            )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electronico..',
                }
            )
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields=("__all__")

Enhanced_blog/apps/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    CreateView
)
#apps Entries
from apps.entries.models import Entry

#
from .models import Home
from .forms import subscriberForm, ContactForm

class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # load home about title and text
        context["about_me"] = Home.objects.latest("created")
        #  im seeing manager file because verified if front
        #  cover and public flag set with true
        # to load image require 3 stufs: the image, in local.py MEDIA_ROOT and
        # add in file principal/urls.py  ] + static............

        # Context for Front_cover in template index.html
        context["cover"] = Entry.objects.front_cover()
        # Context for home entries
        context["home_front_cover"] = Entry.objects.home_front_covers()
        # Context for home items new
        context["new_item_home"] = Entry.objects.home_items_new()
        #send to db the subscriber
        context["subscriber"] = subscriberForm
        return context

class SuscriberCreateView(CreateView):
    form_class = subscriberForm
    success_url = '.'


class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

Enhanced_blog/templates/home/base.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/myblog.css' %}" >
{% endblock css %}

{% block js %}

{% endblock js %}

Enhanced_blog/templates/home/index.html
<!-- head para PC -->
{% extends "home/base.html" %}

{% load  static %}

{% block title %}
    {{about_me.title}}
{% endblock title %}

{% block description %}
    <meta name="description" content="{{about_me.description}}">
{% endblock description %}

{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{cover.image.url}}">
                <div class="card-section">
                  <h4><a href="{% url 'urls_entries:Entry' cover.slug%}">{{cover.title}}</a></h4>
                  <p>{{cover.resume}}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">
            {% for items in home_front_cover %}
            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%;">
                    <img src="{{items.image.url}}" style="height: 140px;">
                    <div class="card-section">
                      <h5><a href="{% url 'urls_entries:Entry' items.slug %}">{{items.title|truncatechars:22}}</a></h5>
                      <p>{{items.resume|truncatechars:50}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->
    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>{{about_me.about_title}}:</h5>
            <p>
                {{about_me.about_text}}
            </p>
            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="POST" action="{% url 'home_app:new_subscriber' %}"> {% csrf_token %}
                    <div class="cell small-12">
                        {{subscriber}}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>
        {% for items_new in new_item_home %}
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%;">
                <img src="{{items_new.image.url}}"  style="height: 220px;">
                <div class="card-section">
                  <!-- <h4>{{items_new.title|truncatechars:22}}</h4> -->
                  <h4><a href="{% url 'urls_entries:Entry' items_new.slug %}">{{items_new.title|truncatechars:22}}</a></h4>
                  <p>{{items_new.resume|truncatechars:50}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}