Enhanced_blog/Enhanced_blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
#SEO
from django.contrib.sitemaps.views import sitemap
from apps.home.sitemap import (
    EntrySitemap,
    Sitemap
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.home.urls')),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.entries.urls')),
    re_path('', include('apps.favorites.urls')),
    #urls to ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'home_app:home'
        ]
    ),
    'entries': EntrySitemap,
    # se agregan mas urls aca se crea el sitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml/',
        sitemap,
        {
            'sitemaps': sitemaps
        },
        name='django.contrib.sitemaps.views.sitemap'
        )   
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Enhanced_blog/apps/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name='user-update-password',
    ),
    path(
        'updateUser/<pk>/',
        views.UpdateUserView.as_view(),
        name='basic_information_user_update'
    ),
    path(
        'incorrect!!/',
        views.IconcorrectPassword.as_view(),
        name = "incorrect-password"
    ),
    path(
        'contraseñaOlvidada/',
        views.RecoverPasswordListView.as_view(),
        name='forgot-password'
    )
]

Enhanced_blog/apps/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )
    avatar_name = models.CharField(unique=True, blank=True, max_length=30)
    avatar_image = models.ImageField(("Imagen Perfil"), upload_to='avatars', blank=True)
    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    ocupation = models.CharField(
        'Ocupacion',
        max_length=30, 
        blank=True
    )
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

Enhanced_blog/apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña'
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'full_name',
            'ocupation',
            'genero',
            'date_birth',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs= {
                    'placeholder': 'Email',
                    },
            ),
            'full_name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombres',
                }
            ),
            'ocupation': forms.TextInput(
                attrs={
                    'placeholder': 'Ocupacion',
                }
            ),
            'date_birth': forms.DateInput(
                attrs={
                    'type': 'date',
                }
            ),
        }
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Correo Electronico',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data


class UpdatePasswordForm(forms.Form):

    user_password = forms.CharField(
        label='Contraseña Actual',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual',
            }
        )
    )
    new_password1 = forms.CharField(
        label='Contraseña Nueva',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva',
            }
        )
    )
    new_password2 = forms.CharField(
        label='repita la Contraseña Nueva',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva',
            }
        )
    )

    def clean_password2(self):
        if self.cleaned_data['new_password1'] != self.cleaned_data['new_password2']:
            self.add_error('new_password2', 'Las contraseñas no son iguales')

class UserFieldEmail(forms.Form):
    # crear un campo para validar en el views
    email = forms.EmailField(
        label = "Ingrese email",
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Ingrese su email',
                'autocomplete': 'off',
            }
        )
        )

Enhanced_blog/apps/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse

from django.views.generic import (
    View,
    CreateView,
    UpdateView,
    TemplateView,
    ListView
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm, 
    LoginForm,
    UpdatePasswordForm,
)
#
from .models import User
# 


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name=form.cleaned_data['full_name'],
            ocupation=form.cleaned_data['ocupation'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('favorites_app:profile')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['user_password']
        )

        if user:
            new_password = form.cleaned_data['new_password2']
            usuario.set_password(new_password)
            usuario.save()
        else:
            return HttpResponseRedirect(
                reverse("users_app:incorrect-password")
            )

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)

class UpdateUserView(LoginRequiredMixin, UpdateView):
    template_name = "favorites/updateUser.html"
    model = User
    login_url = reverse_lazy('users_app:user-login')
    
    fields = [
        'avatar_name',
        'avatar_image',
        'full_name',
        'ocupation',
        'genero'
    ]
    success_url = reverse_lazy('favorites_app:profile')

    def form_valid(self, form):
        return super(UpdateUserView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(UpdateUserView, self).post(request, *args, **kwargs)


class IconcorrectPassword(TemplateView):
    template_name = "users/incorrectPassword.html"

class RecoverPasswordListView(TemplateView):
    template_name = "users/incorrectPassword.html"

        
   
 

Enhanced_blog/templates/users/base.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myCustom.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

Enhanced_blog/templates/users/incorrectPassword.html
{% extends 'users/base.html' %}

{% block title %}
Verificacion de usuario Fallida
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container grid-y grid-padding-y">
        <div class="cell large-3 medium-3">
            <div class="callout primary">
                <div class="grid-y grid-padding-y">
                    <h2>La contraseña original a sido ingresada de forma incorrecta</h2>
                </div>
            </div>
        </div>
    </div>

        
{% include 'includes/footer.html' %}
{% endblock content %}

Enhanced_blog/templates/users/login.html
<!-- head para PC -->
{% extends "users/base.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-6 large-4" style="margin-top: 2em;">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                  <h4>Acceso de usuario</h4>
                </div>
                <div class="card-section">
                    <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                        <div class="cell medium-12">
                            <label>Email:
                            {{form.email}}
                            </label>
                        </div>
                        <div class="cell medium-12">
                            <label>Contraseña:
                            {{form.password}}
                            </label>
                        </div>
                        <button type="submit" class="cell hollow button primary">Acceder</button>
                        <a class="cell hollow button alert" href="{% url 'users_app:user-register' %}">Registrar</a>
                    </form>
                </div>
                <h5 class="text-center"><a href="{% url 'users_app:forgot-password' %}">¿Olvido su contraseña?</a></h5>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Enhanced_blog/templates/users/register.html
<!-- head para PC -->
{% extends "users/base.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-10 large-6" style="margin-top: 2em;">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                  <h4>Ingrese sus datos</h4>
                </div>
                <div class="card-section">
                    <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                        {% comment %} {% if form.errors %}
                        <p>
                        {{form.errors}}
                        </p>
                        {% endif %} Muestra errores si existen dentro del formulario{% endcomment %}




                        <div class="cell large-12">
                            <label>Email:
                            {{ form.email }}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Nombres:
                            {{ form.full_name }}
                            </label>
                        </div>
                        <div class="cell medium-6">
                            <label>Ocupacion:
                            {{ form.ocupation }}
                            </label>
                        </div>
                        <div class="cell medium-6">
                            <label>Genero:
                            {{ form.genero }}
                            </label>
                        </div>
                        <div class="cell medium-6">
                            <label>Fecha Nacimiento:
                            {{ form.date_birth }}
                            </label>
                        </div>
                        <div class="cell medium-12">
                            <label>Contraseña:
                            {{ form.password1 }}
                            </label>
                        </div>
                        <div class="cell medium-12">
                            <label>Repetir Contraseña:
                            {{ form.password2 }}
                            {% for e in form.password2.errors %}
                                <p style="color: red;"> {{ e }}</p>
                            {% endfor %}
                            </label>
                        </div>
                        <button type="submit" class="cell hollow button primary">Registrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Enhanced_blog/templates/users/update.html
{% extends 'users/base.html' %}
{% block title %} Cambio de contraseña {% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
        
        <div class="grid-container grid-x">
            <div class="cell large-4 align-center"></div>
            <form class="large-4 align-center" method="POST", autocomplete="new-password">{% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="button warning">Guardar Nueva Contraseña</button>
            </form>
        </div>
    {% include 'includes/footer.html' %}
{% endblock content %}