Enhanced_blog/Enhanced_blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
#SEO
from django.contrib.sitemaps.views import sitemap
from apps.home.sitemap import (
    EntrySitemap,
    Sitemap
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.home.urls')),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.entries.urls')),
    re_path('', include('apps.favorites.urls')),
    #urls to ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'home_app:home'
        ]
    ),
    'entries': EntrySitemap,
    # se agregan mas urls aca se crea el sitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml/',
        sitemap,
        {
            'sitemaps': sitemaps
        },
        name='django.contrib.sitemaps.views.sitemap'
        )   
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Enhanced_blog/apps/entries/urls.py
from django.urls import path

from . import views

app_name = 'urls_entries'

urlpatterns = [
    path(
        'Lista_blogs/',
        views.EntryListView.as_view(),
        name = "blog_list"
        ),
    path(
        'blog/<slug>',
        views.EntryDetailView.as_view(),
        name = "Entry"
        ),
]

Enhanced_blog/apps/favorites/urls.py
from django.urls import path

from . import views

app_name = "favorites_app"

urlpatterns = [
    path(
        'profile',
        views.FavoritesListView.as_view(),
        name = "profile"
        ),
    path(
        'add_favorites/<pk>',
        views.AddFavoriteView.as_view(),
        name = "add-favorites"
        ),
    path(
        'deletefavorites/<pk>/',
        views.FavoriteDeleteView.as_view(),
        name = "delete-favorites"
        )
    
]

Enhanced_blog/apps/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name='user-update-password',
    ),
    path(
        'updateUser/<pk>/',
        views.UpdateUserView.as_view(),
        name='basic_information_user_update'
    ),
    path(
        'incorrect!!/',
        views.IconcorrectPassword.as_view(),
        name = "incorrect-password"
    ),
    path(
        'contraseñaOlvidada/',
        views.RecoverPasswordListView.as_view(),
        name='forgot-password'
    )
]

Enhanced_blog/apps/favorites/models.py
from django.db import models
from django.conf import settings

#trhid apps
from model_utils.models import TimeStampedModel
#our Apps
from apps.entries.models import Entry
from .managers import favoritesManager

class Favorite(TimeStampedModel):
    """Model for favorites"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_favorites',
        on_delete=models.CASCADE
        )
    entry = models.ForeignKey(
        Entry,
        related_name="entry_favorites",
        on_delete=models.CASCADE
        )
    objects = favoritesManager()
    class Meta:
        unique_together = ('user', 'entry')
        # user only save unique entry does not repeated
        verbose_name = 'Entrada faborita'
        verbose_name_plural = 'Entradas faboritas'

    def __str__(self):
        return self.entry.title
    

Enhanced_blog/apps/favorites/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect



from django.views.generic import (
    ListView,
    View,
    DeleteView
    )

from .models import Favorite
from apps.users.models import User
from apps.entries.models import Entry


class FavoritesListView(LoginRequiredMixin, ListView):
    template_name = "favorites/profile.html"
    context_object_name = "detail_account"
    login_url = reverse_lazy('users_app:user-login')

    def get_context_data(self, **kwargs):
        context = super(FavoritesListView, self).get_context_data(**kwargs)
        email = User.objects.cut_email(self.request.user.id)
        # email = User.objects.annotate(last_letter=Right('email',9)).get(id=self.request.user.id)
        context['emailModified'] = email
        
        return context
    
    def get_queryset(self):
        return Favorite.objects.favorites_user(self.request.user)


class AddFavoriteView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users_app:user-login')

    def post(self, request, *args, **kwargs):
        request_user = self.request.user
        favorite_entry = Entry.objects.get(id=self.kwargs['pk'])

        Favorite.objects.create(
            user = request_user,
            entry = favorite_entry
        )
        return HttpResponseRedirect(
            reverse('favorites_app:profile')
        )


class FavoriteDeleteView(DeleteView):
    model = Favorite
    success_url = reverse_lazy('favorites_app:profile')
            

Enhanced_blog/templates/favorites/base.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

Enhanced_blog/templates/favorites/profile.html
<!-- head para PC -->
{% extends "favorites/base.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{user.full_name}}</h5>
                <p>este es:{{emailModified}} - {{user.ocupation}} - {{user.date_birth}}</p>
                <a href="{% url 'users_app:basic_information_user_update' user.id%}" class="hollow button alert">Editar Datos</a>
                <a href="{% url 'users_app:user-update-password' user.id%}" class="hollow button alert">Cambiar contraseña</a>
                <a href="{% url 'users_app:user-logout' %}" class="hollow button alert"> Salir</a>
                
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->
        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            <div class="cell small-12">
                {% for i in detail_account %}
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{i.entry.image.url}}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{i.entry.title}}</h3>
                        <p> {{i.entry.resume|truncatechars:160}} </p>
                        <form class="card-favoritos-body-actions" method="POST" action="{% url 'favorites_app:delete-favorites' i.id %}"> {% csrf_token %}
                            <a class="button warning" href="{% url 'urls_entries:Entry' i.entry.slug %}">Ver</a>
                            <button type="submit" class="button alert">Eliminar</button>
                        </form>
                    </div>
                </div>
                {% empty %}
                <h2>
                    No tienes ningun articulo favorito
                </h2>
                {% endfor %}
            </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
        </div>
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

Enhanced_blog/templates/favorites/updateUser.html
{% extends "favorites/base.html" %}

{% load static %}

{% block content %}
    {% include 'includes/header.html' %}
    
<div class="grid-container grid-y grid-padding-y">
    <div class="cell large-3 medium-3">
        <div class="callout primary grid-margin-y">
            <div class="grid-y grid-padding-y">
                <h2 class="text-center">Actualizar Datos</h2>
            </div>
        </div>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <ul>
            <li>
            <h3>avatar</h3>
            {{form.avatar_name}}
            </li>
            <li>
            <h3>imagen</h3>
            {{form.avatar_image}}
            </li>
            <li>
            <h3>nombre completo</h3>
            {{form.full_name}}
            </li>
            <li>
            <h3>ocupacion</h3>
            {{form.ocupation}}
            </li>
            <li>
            <h3>genero</h3>
            {{form.genero}}
            </li>
        </ul>
            <div class="grid-x grid-margin-x">
                <div class="cell medium-4 large-5"></div>
                <div class="cell medium-4 large-5">
                    <button class="button primary" type="submit">Guardar Cambios</button>
                </div> 
            </div>
    </form>
    </div>
</div>

    {% include 'includes/footer.html' %}
{% endblock content %}